### ISSUE TITLE
BUG: Incorrect scrobbling when using higher playback speed

### ISSUE THREAD

**Issue by ITSYV** [trakt-tools/universal-trakt-scrobbler#102]
When using a higher playback speed (ex. 2x - with a plugin), the scrobbling seems to be incorrect.
I noticed this on a Netflix show and on Prime.

I also get an error in console 'traktflix: Scrobble error undefined undefined undefined"
Not sure if this is due to the series: Outer banks s01e03 on Netflix -> shows "pilot" in traktflix

**Comment by rafaelgomesxyz** [comment]
In what sense is it incorrect? Like it scrobbles with the wrong progress?

**Comment by ITSYV** [comment]
@rafaelgomesxyz Sometimes lagging behind 1 or more episodes.
I am using an extension "video speed controller" on chrome/brave

**Comment by rafaelgomesxyz** [comment]
I think it was actually a critical bug that I found that was using the wrong ID for episodes on Netflix (it was using the ID for the show instead). So if you watched an episode and within 45 minutes watched another episode from the same show, it would still scrobble the previous episode, since they had the same ID. The reason why no one else aside from you appears to be experiencing this issue (otherwise I'd assume they'd have reported it already) is because since you're watching in 2x speed, you get to the next episode before the 45-minute cache is updated. This should explain why you were watching S1 E3 and it was still scrobbling S1 E1.

Please test the `.zip` files provided in the PR and confirm: https://github.com/trakt-tools/universal-trakt-scrobbler/pull/161
