### ISSUE TITLE
Update to manifest v3

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#156]
Manifest v2 is deprecated and no longer accepted for releases:
https://developer.chrome.com/blog/mv2-transition/

This rewrite is required for #147

**Comment by rafaelgomesxyz** [comment]
This will be a bit of a problem because of how we use the background page at the moment, but I'll try to figure something out.

**Comment by rafaelgomesxyz** [comment]
Will try to tackle this. From an initial observation, this is what needs to be done:

- [x] General changes to the manifest file. These will probably not be that difficult, as it's mostly renaming things and moving things around.
- [ ] Adapt any logic that required the background page to stay active (service workers go inactive after a while). Most of this is probably achievable by storing the data with `browser.storage` and then getting it when needed. Major refactor.
- [x] Adapt script injections to use `scripting.executeScript`. Small refactor.
- [x] Adapt any code that ran in intervals to use `browser.alarms` (like auto sync and cache checks running every hour). Small refactor.
- [ ] Adapt usages of `webRequest` to the new `declarativeNetRequest`. This one might be the more annoying one, but since `webRequest` is only used for Firefox, and only when using containers, I might just ignore it for now.
