### ISSUE TITLE
Merge with scrobbler or third repo with common code?

### ISSUE THREAD

**Issue by rafaelgomesxyz** [trakt-tools/universal-trakt-scrobbler#19]
There's a lot of code that will be duplicated between the scrobbler and the sync extensions. In order to reduce that, I can think of two solutions:

* Merge both extensions (it's not like the size is that much bigger, and users might prefer to have a single extension installed rather than multiple ones)
* Create a third repo to host common code (which we then publish as a package and use as a dependency for each extension)

What do you think?

**Comment by MrMamen** [comment]
Hmm. Yeah I think it is important to reduce duplicate code. It's a tough call. I'll just try to write some arguments for each below:

Crate a third repo:
- the services that scrobble and those who sync history may not be the same. (Both because of missing APIs and also because a developer has to do the job.)
- It might be easier to understand and work with the code when it's not too complex.
- Someone that's not a developer might find it easier to translate or do other simpler tasks it this is located in a thin repo.

Merge:
- Just having two extensions that has some overlap is a waste of space. People interested in one is probably also interested in the other.
- The reason I wanted to split them in the first place was really because I thought it was too much work to create both at the same time.
- Potentially you need three commits to change small bugs, with three repos.

**Comment by MrMamen** [comment]
Personally I have a small preference for merging the code bases. Should still aim for having a clean code though.

**Comment by rafaelgomesxyz** [comment]
I also prefer merging. I'll see if I can start working on it. This repo is more advanced than the scrobbler, so it makes more sense to merge the scrobbler here. But at the same time, I think 'Universal Trakt Scrobbler' is a better name than 'Universal Trakt Sync'. Maybe we can just merge the scrobbler here and rename the repo.

**Comment by MrMamen** [comment]
I agree with you.
