### ISSUE TITLE
HBO Max doens't show what i'm watching, i have to manually sync everything later

### ISSUE THREAD

**Issue by hrqmonteiro** [trakt-tools/universal-trakt-scrobbler#268]
### Expected Behavior

Show what i am watching and syncing automatically.

### Current Behavior

Not doing it.

### Steps to Reproduce

COnfigured everything right, am logged with Trakt and synced everything left to Sync.

### Additional Information

- **OS + Version:** macOS Ventura
- **Browser + Version:** Firefox 109.0
- **Country/Region:** Brazil

![Screenshot 2023-01-24 at 22 40 05](https://user-images.githubusercontent.com/17055027/214461440-03ae5212-5ebd-44a1-b08a-75d2b0c80b0f.png)
![Screenshot 2023-01-24 at 22 42 10](https://user-images.githubusercontent.com/17055027/214461534-683f0a57-8aa1-4bd5-b430-e0f14433f514.png)

**Comment by tomck** [comment]
I am having this issue presently on Firefox 112.0.2 with extension version 0.2.2 from the Firefox addons "store". What debug info can I provide to help? (I can go in and manually sync, but I wanted the automatic scrobbling feature, of course.)

Edit: It turns out that it just wasn't scrobbling for BBC's Ghosts, it is now scrobbling just fine for Call Me Kat.

Edit again: It stopped scrobbling after the first episode, I have had to manually sync history again.
