### ISSUE TITLE
Add support for other Viaplay on other domains

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#29]
Currently viaplay is hardcoded to use viaplay.no
It needs to also support:
http://viasat.se/
http://viasat.dk/
http://viasat.fi/

If possible this should be automatically detected: Probably by opening viaplay.com and see where it is redirected.

**Comment by MrMamen** [comment]
I'm pretty much stuck on this because I'm unable to inject script and read content from another page. It could of course be done by cloning (sharing) code base, and just adjust the baseURL in each case, but I feel this is a last resort as it clutters the list.

**Comment by rafaelgomesxyz** [comment]
Well, isn't it possible to do what you mentioned before? Make a request to `https://viaplay.com` and see where it redirects to?

**Comment by MrMamen** [comment]
It's a good idea, but I have no idea how to make it work. I think I've mentioned this on email earlier, but I tried to base this on your hbo-go-code, but the executeScript seems to fail, at least in chrome, and then I have figure out an alternative.

**Comment by rafaelgomesxyz** [comment]
You shouldn't need to inject any script. Unless I'm misunderstanding, you just need to make a request:

```
const response = await fetch('https://viaplay.com');
```

It should automatically redirect and you should find the new URL in `response.url` (for me I got `https://viaplay.se/`).

Of course you would need to add permission for `https://viaplay.com` to the manifest because of CORS. And I'm not sure, but you might have to add permissions for each possible variation too (not sure, might be best to try without doing this first).

**Comment by MrMamen** [comment]
Right, that seems like a much easier approach than my complicated one. ;-)
