### ISSUE TITLE
Fix Netflix sync time

### ISSUE THREAD

**Issue by rafaelgomesxyz** [trakt-tools/universal-trakt-scrobbler#44]
The Netflix watched date is always when the user began watching, not when they finished. We should change that by adding the length of the episode/movie to the watch date, so it's more accurate.

**Comment by MrMamen** [comment]
Possible as an user option?

**Comment by rafaelgomesxyz** [comment]
Well, I can't see why anyone would want it to behave like it does currently, since the watch time is always wrong. But sure, we can add it as an option, enabled by default.

**Comment by MrMamen** [comment]
I think this is a case with pretty much all streaming services. It records the last time the play-button was clicked, or similar. The problem is of course if you watch a part of the title at one point, and resumes at another time. Not sure if it's worth making a lot of UI for, but at least it is a concern.
Also there are a few similar off situations.
If you use trakt "add on release date"-feature, it would record the start time. Scrobling and checkins would record the end time. I guess it is a matter of definition, and not sure if it is important. I don't have any strong opinions of this.
