### ISSUE TITLE
Not able to disable streaming services with scrobble

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#51]
The streaming services which support scrobbling is unable to deactivate once activated.

**Comment by rafaelgomesxyz** [comment]
Isn't this that problem we discussed a while ago that was most likely because of how unpacked Chrome extensions work?

**Comment by MrMamen** [comment]
Yes, but I'm not so sure if that is the case. It doesn't make any sense why there should be difference between unpacked extensions and others. Unless you have tested this or have pinpointed this to a specific location I think we should leave this here. I'll see if I can look into it.

**Comment by rafaelgomesxyz** [comment]
The difference is that in unpacked extensions all permissions are considered as required for some reason. So when you try to disable a streaming service and it tries to remove the permissions for that service, it fails with this message: `You cannot remove required permissions.`

The reason why I'm quite positive that that's the case is because I can disable them just fine on Firefox.

But if you think it's something else, then let me know what you find.

**Comment by MrMamen** [comment]
But you need the same host-permissions for history-sync, and it doesn't fail to disable NRK or Viaplay which has sync-only.

**Comment by rafaelgomesxyz** [comment]
That might just be a coincidence, I tried setting `hasScrobbler` to false on Netflix and I still wasn't able to disable it.

And like I said, I can disable all of them on Firefox, so this is definitely a Chrome issue.

**Comment by rafaelgomesxyz** [comment]
Oh, I just thought of something, it might be because the scrobblers have to inject content in the page, so we have an entry for them in `content_scripts` and Chrome detects that as a required permission. A solution to this would be to dynamically inject scripts instead of defining them in the manifest.

**Comment by MrMamen** [comment]
nice work. Now I think we are starting to pinpoint the issue.!

**Comment by rafaelgomesxyz** [comment]
Firefox has a nice API for this (`browser.contentScripts`), but for cross-browser compatibility we'll probably have to use a combination of `chrome.tabs.onCreated` / `chrome.tabs.onUpdated` and `chrome.tabs.executeScript` in the background page.
